In [1]:
from scipy.stats import norm
import numpy as np
print(norm.ppf(np.array([1,-1., 0, 1, 3, 4, -2, 6])))

[ inf  nan -inf  inf  nan  nan  nan  nan]


In [2]:
print(norm.rvs(size = 5))

[-0.22384801 -1.58330655 -1.97651734  0.02175291  0.74523283]


In [3]:
from scipy.stats import uniform
uniform.cdf([0, 1, 2, 3, 4, 5], loc = 1, scale = 11)

array([0.        , 0.        , 0.09090909, 0.18181818, 0.27272727,
       0.36363636])

In [4]:
from scipy import stats
import numpy as np
x = np.array([1,2,3,4,5,6,7,8,9])
print(x.max(),x.min(),x.mean(),x.var(), x.std())

9 1 5.0 6.666666666666667 2.581988897471611


In [7]:
print (norm.cdf(np.array([1,-2,0,4,5,3])))

[0.84134475 0.02275013 0.5        0.99996833 0.99999971 0.9986501 ]


In [31]:
#Ttest_1
from scipy import stats
rvs = stats.norm.rvs(loc = 1, scale = 1, size = (50,2))

stats.ttest_1samp(rvs,5.0)

Ttest_1sampResult(statistic=array([-29.56615672, -28.47765772]), pvalue=array([6.70716110e-33, 3.81706076e-32]))

In [34]:
from scipy import stats
rvs1 = stats.norm.rvs(loc = 1,scale = 1,size = 500)
rvs2 = stats.norm.rvs(loc = 5,scale = 10,size = 500)
stats.ttest_ind(rvs1,rvs2)

Ttest_indResult(statistic=-8.410866609049963, pvalue=1.3943578323451487e-16)

# One Tail Test

In [47]:
data1=uniform.cdf([1,2,3,4,5,6,7,8,9,10],loc=2,scale=3)
data

array([ 1.84954497, -1.08287627,  3.39966115, -1.66945763,  3.43388751,
       -1.57046543, -0.67961578,  0.69031832,  1.6670603 ,  3.2579928 ])

In [48]:
data2=stats.norm.rvs(loc=1,scale=3,size=10)
data

array([ 1.84954497, -1.08287627,  3.39966115, -1.66945763,  3.43388751,
       -1.57046543, -0.67961578,  0.69031832,  1.6670603 ,  3.2579928 ])

In [46]:
#This gives two tail test p value so divide by 2 to get final p-value
p=scipy.stats.ttest_1samp(data,0.3)[1]
p_value= p/2
p_value

0.181584177045724

In [49]:
stats.ttest_ind( data1,data2)

Ttest_indResult(statistic=1.4806150669742029, pvalue=0.15600106857053078)

In [50]:
#Proportion Test
import statsmodels.api as sm
sm.stats.ttest_ind( data1,data2)

(1.4806150669742029, 0.15600106857053078, 18.0)